const RouteStrings = {
    home: '/home',
    test: '/test',
    song: '/song/',
    search: '/search',
    favorite: '/favorite',
    account: '/account',
    playlist: '/playlist/',
    albums: '/albums/',
    artist: '/artist/',
    artistDetails: '/artistDetails',
    artistSongs: '/',
    artistAlbums: '/albums',
    selectLanguage: '/selectLanguage',
    updateLanguage: '/updateLanguage',
    myMusic: '/myMusic',
    recentlyPlayed: '/myMusic',
    myfavorites: '/myMusic/myFavorites',
    myPlayLists: '/myMusic/myPlayLists',
    noNetwork: '/noNetwork',
    userPlaylist: '/userPlaylist/',


    register: '/auth/register',
    login: '/auth/login',
    otp: '/auth/otpverification',
    changePassword: '/auth/changepassword',
    forgotPassword: '/auth/forgotPassword',
}
export default RouteStrings